apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: multi-k8s-techwings-io-tls
spec:
  secretName: multi-k8s-techwings-io
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: multi-k8s.techwings.io
  dnsNames:
    - multi-k8s.techwings.io
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - multi-k8s.techwings.io
